/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-09-10 06:26:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hk.dtos.UserDto;

public final class registform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1725941525238L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1725949581788L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.hk.dtos.UserDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");

	response.setHeader("Pragma", "no-cache");
	response.setHeader("Cache-Control", "no-cache");
	response.setHeader("Cache-Control", "no-store");
	response.setDateHeader("Expires", 0L);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
request.setCharacterEncoding("utf-8"); 
      out.write('\r');
      out.write('\n');
response.setContentType("text/html;charset=UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layout.css\">\r\n");
      out.write("</head>\r\n");

	//현재 path 확인해보기
	System.out.println(request.getRequestURI());
	System.out.println(request.getRequestURI().substring(
				request.getContextPath().length()
			));

	UserDto ldto=null;
	
	String requestPath=
	request.getRequestURI().substring(request.getContextPath().length());
	
	if(!requestPath.equals("/registform.jsp")){
		ldto=(UserDto)session.getAttribute("ldto");
	
		//로그인 정보가 없는 경우(로그아웃한 경우) 화면처리 
		if(ldto==null){
			pageContext.forward("index.jsp");
		}		
	}
// 	hkcontroller.jsp/admin/*    --> 로그인정보확인해서 볼수 있는 페이지
// 	hkcontroller.jsp/user/login --> 로그인정보확인해서 볼수 있는 페이지
// 	hkcontroller.jsp/user/regist--> 로그인정보확인X

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar\">\r\n");
      out.write("	<div id=\"navbar\">\r\n");
      out.write("		<ul class=\"navbar-nav\">\r\n");
      out.write("			<li><a href=\"index.jsp\">HOME</a></li>\r\n");
      out.write("			<li>ABOUT</li>\r\n");
      out.write("			<li>CONTECT</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>회원가입 폼</title>\r\n");
      out.write("<!-- <link rel = \"stylesheet\" href=\"css/layout.css\"> -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class = \"navbar\">\r\n");
      out.write("	<div id = \"navbar\">\r\n");
      out.write("		<ul class =\"navbar-nav\">\r\n");
      out.write("			<li><a href = \"index.jsp\">HOME</a></li>\r\n");
      out.write("			<li>about</li>\r\n");
      out.write("			<li>CONTECT</li>\r\n");
      out.write("		\r\n");
      out.write("		</ul>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<div>\r\n");
      out.write("	<h1>회원가입</h1>\r\n");
      out.write("	<form action = \"userController.jsp\" method = \"post\" onsubmit = \"return isPW(this)\">\r\n");
      out.write("	<input type = \"hidden\" name = \"command\" value = \"adduser\"/>\r\n");
      out.write("	<input type = \"text\" name = \"id\" placeholder=\"ID\" required = \"required\"/>\r\n");
      out.write("	<a href = \"#\" onclick = \"idChk()\">중복체크</a>\r\n");
      out.write("	<input type = \"text\" name = \"name\" placeholder=\"이름\" required = \"required\"/>\r\n");
      out.write("	<input type = \"password\" name = \"password\" placeholder=\"PASSWORD\" required = \"required\"/>\r\n");
      out.write("	<input type = \"password\" name = \"password2\" placeholder=\"PASSWORD확인\" required = \"required\"/>\r\n");
      out.write("	<input type = \"text\" name = \"address\" placeholder=\"ADDRESS\" required = \"required\"/>\r\n");
      out.write("	<input type = \"email\" name = \"email\" placeholder=\"EMAIL\" required = \"required\"/>\r\n");
      out.write("	<button type = \"submit\">가입완료</button>\r\n");
      out.write("	<button type = \"button\" onclick = \"location.href = 'index.jsp'\">메인</button>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- <div class = \"footer\">\r\n");
      out.write("	Coptright 1999-2024. 한경닷컴 ALL rights reserved.\r\n");
      out.write("</div>  -->\r\n");
      out.write("<script type = \"text/javascript\">\r\n");
      out.write("function isPW(formEle){ //파라미터는 form 엘리먼트 전달 받음 안 그러면 var foremEle = document.getElementByTagName(\"form\")[0]을 써야함\r\n");
      out.write("	if(formEle.paswword.value!=foremEle.password2.value){\r\n");
      out.write("		alert(\"비밀번호를 확인하세요\");\r\n");
      out.write("		formEle.password.value=\"\"; // 비밀번호 초기화\r\n");
      out.write("		formEle.password2.value=\"\";\r\n");
      out.write("		formEle.password.focus(); //비밀번호 바로 입력할 수 있도록 유도 -> 커서 넣기\r\n");
      out.write("		return false; // false 반환해줘야 submit 취소할 수 있다. (지금페이지를 유지한다는 것)\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function idChk(){\r\n");
      out.write("	var id = document.getElementsByName(\"id\")[0].value;\r\n");
      out.write("	if(id==\"\"){\r\n");
      out.write("		alert(\"아이디를 입력하세요\");\r\n");
      out.write("	}else{\r\n");
      out.write("		window.open(\"userController.jsp?command=idchk&id=\"+id,\"아이디확인\",\"width=300px,height=300px\");\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class = \"footer\">\r\n");
      out.write("	Coptright 1999-2024. 한경닷컴 ALL rights reserved.\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
